import './globals.css'

export const metadata = {
  title: 'Jornades PAD',
  description: 'Generated by la NUT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ca">
      <body>{children}</body>
    </html>
  )
}
